[package]
name = "samp"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[features]
default = []
encoding = ["samp-sdk/encoding"]

[dependencies]
samp-sdk = { path = "../samp-sdk" }
samp-codegen = { path = "../samp-codegen" }
fern = "0.5.7"