[package]
name = "timers"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
samp = { path = "../../samp", features = ["async"] }
tokio = "0.1.17"
log = "0.4.6"